#!/usr/bin/env python3
# luxarch:cmdtext hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Shared: the EXECUTABLE part of a shell command, with data spans masked out.

luxarch's own line-regex rules run through `core._masked_lines`, which blanks string and comment
spans so an example inside a docstring cannot trip a rule. A Bash hook needs the same doctrine: a
heredoc body and a quoted literal are DATA the command carries, not the command being run. Without
it the hooks matched raw text, so writing a test or a doc ABOUT a dangerous pattern read as
executing it — that blocked routine work, and then blocked their own repair.

Masked (replaced by spaces so offsets and line numbers survive):
  * heredoc bodies -- <<EOF ... EOF, <<'EOF' ... EOF, <<-EOF
  * single-quoted spans
  * double-quoted spans
"""

import re

_HEREDOC = re.compile(r"<<-?\s*(['\"]?)(\w+)\1(.*?)^\s*\2\s*$", re.S | re.M)
_SQ = re.compile(r"'[^']*'")
_DQ = re.compile(r'"[^"]*"')


def _blank(m: re.Match[str]) -> str:
    return "".join("\n" if c == "\n" else " " for c in m.group(0))


def command_text(cmd: str) -> str:
    """`cmd` with heredoc bodies and quoted literals blanked -- what is actually EXECUTED."""
    if not cmd:
        return ""
    out = _HEREDOC.sub(_blank, cmd)
    out = _SQ.sub(_blank, out)
    return _DQ.sub(_blank, out)


_SEGMENT = re.compile(r"&&|\|\||;|\n|\|")


def segments(cmd: str) -> list[tuple[str, str]]:
    """(masked, raw) pairs, one per command segment.

    Two different questions need two different texts. "Is this dangerous verb actually being run?"
    must be asked of MASKED text, or a quoted example reads as an execution. "What is it pointing
    at?" must be asked of RAW text, or a quoted path vanishes and an unambiguous scratch target
    looks like an unknown one.

    Masking preserves length, so a boundary found in the masked string indexes the raw string too.
    """
    if not cmd:
        return []
    masked = command_text(cmd)
    out: list[tuple[str, str]] = []
    start = 0
    for m in _SEGMENT.finditer(masked):
        out.append((masked[start : m.start()], cmd[start : m.start()]))
        start = m.end()
    out.append((masked[start:], cmd[start:]))
    return out
