#!/usr/bin/env python3
# luxarch:cmdtext hook v2 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Shared: the EXECUTABLE part of a shell command, with data spans masked out.

luxarch's own line-regex rules run through `core._masked_lines`, which blanks string and comment
spans so an example inside a docstring cannot trip a rule. A Bash hook needs the same doctrine: a
heredoc body and a quoted literal are DATA the command carries, not the command being run. Without
it the hooks matched raw text, so writing a test or a doc ABOUT a dangerous pattern read as
executing it — that blocked routine work, and then blocked their own repair.

Masked (replaced by spaces so offsets and line numbers survive):
  * heredoc bodies -- <<EOF ... EOF, <<'EOF' ... EOF, <<-EOF
  * single-quoted spans
  * double-quoted spans
"""

import re

# The body starts on the NEXT line: after `<<TAG` the REST OF THAT LINE is still command, so a
# redirect or argument written after the marker — `python3 - <<'PY' > app/x.py` — is executable text,
# not data. The first cut captured from the marker to the terminator and blanked the whole span, so
# that redirect vanished from the masked text: five Bash hooks could not see the target of a command
# whose heredoc came first. Groups: 1 = marker + rest of line, 3 = TAG, 4 = BODY, 5 = terminator.
_HEREDOC = re.compile(r"(<<-?\s*(['\"]?)(\w+)\2[^\n]*\n)(.*?)(^\s*\3\s*$)", re.S | re.M)
_SQ = re.compile(r"'[^']*'")
_DQ = re.compile(r'"[^"]*"')


def _blank(m: re.Match[str]) -> str:
    return "".join("\n" if c == "\n" else " " for c in m.group(0))


def _blank_body(m: re.Match[str]) -> str:
    """Blank ONLY the heredoc body, keeping the marker line and terminator as command text."""
    return m.group(1) + _blank_str(m.group(4)) + m.group(5)


def _blank_str(text: str) -> str:
    return "".join("\n" if c == "\n" else " " for c in text)


def command_text(cmd: str) -> str:
    """`cmd` with heredoc bodies and quoted literals blanked -- what is actually EXECUTED."""
    if not cmd:
        return ""
    out = _HEREDOC.sub(_blank_body, cmd)
    out = _SQ.sub(_blank, out)
    return _DQ.sub(_blank, out)


_SEGMENT = re.compile(r"&&|\|\||;|\n|\|")


def segments(cmd: str) -> list[tuple[str, str]]:
    """(masked, raw) pairs, one per command segment.

    Two different questions need two different texts. "Is this dangerous verb actually being run?"
    must be asked of MASKED text, or a quoted example reads as an execution. "What is it pointing
    at?" must be asked of RAW text, or a quoted path vanishes and an unambiguous scratch target
    looks like an unknown one.

    Masking preserves length, so a boundary found in the masked string indexes the raw string too.
    """
    if not cmd:
        return []
    masked = command_text(cmd)
    out: list[tuple[str, str]] = []
    start = 0
    for m in _SEGMENT.finditer(masked):
        out.append((masked[start : m.start()], cmd[start : m.start()]))
        start = m.end()
    out.append((masked[start:], cmd[start:]))
    return out


# ── The INVERSE lens: what a command WRITES ─────────────────────────────────────────────────────
# `command_text` masks the data to ask "is this verb being run?". A content guard needs the opposite:
# the data IS the subject. Four PreToolUse hooks — no-suppression, no-test-weakening, no-golden-edit,
# no-agent-deferral — were matched on `Edit|Write` only, so a heredoc through Bash wrote identical
# bytes and fired none of them. The gap was not agents misbehaving: Claude Code's auto mode actively
# recommends shell over the edit tools, so the RECOMMENDED path was the unguarded one, and both the
# LuxPM agent and this maintainer took it for a whole session. luxlint does not close it afterwards
# either — RUF100 only reds a STALE `# noqa`, so one that genuinely suppresses a live PLC0415 passes
# every gate.
#
# What a shell command will put on disk is not decidable in general (a `python3 -` heredoc can
# COMPUTE its output). What IS decidable, and covers every case the fleet has produced, is the
# literal text the command carries: heredoc bodies, a `sed -i` replacement, a redirected `printf`.
# A python heredoc that writes a file contains the forbidden token as a literal, so scanning the
# carried text catches it.
_REDIRECT = re.compile(r"(?:^|\s)(?:\d?>>?|\|\s*tee(?:\s+-a)?)\s+(\S+)")
_SED_INPLACE = re.compile(r"\bsed\b[^|;&\n]*\s-i\b")
# Writes that are not repo edits. A throwaway script in the scratchpad or /tmp is not the subject,
# and /dev/null is not a file.
_NOT_A_REPO_PATH = re.compile(r"^/dev/null$|^/tmp/|/scratchpad/|^\$?\{?TMPDIR")


def _writes_to_a_repo_path(masked: str, raw: str) -> bool:
    """Does this segment put bytes into a file that is part of the repo?

    Asked of the MASKED text for the verb and of the RAW text for the target — the two-lens rule.
    A `grep -rn "noqa" src/` mentions a forbidden token and writes nothing; it must not be flagged,
    or the hook blocks the very audit that finds real suppressions.
    """
    if _SED_INPLACE.search(masked):
        return True
    for m in _REDIRECT.finditer(masked):
        target = raw[m.start(1) : m.end(1)].strip("'\"")
        if target and not _NOT_A_REPO_PATH.search(target):
            return True
    return False


def written_content(cmd: str) -> str:
    """The literal text a Bash command will place into a repo file — '' when it writes nothing.

    Returns the heredoc bodies plus the whole writing segment, because a `sed -i` replacement and a
    redirected `printf` carry their payload inline rather than in a heredoc.
    """
    if not cmd:
        return ""
    writes = any(_writes_to_a_repo_path(m, r) for m, r in segments(cmd))
    if not writes:
        return ""
    parts = [m.group(4) for m in _HEREDOC.finditer(cmd)]
    for masked, raw in segments(cmd):
        if _writes_to_a_repo_path(masked, raw):
            parts.append(raw)
    return "\n".join(parts)


def write_targets(cmd: str) -> list[str]:
    """Repo paths this command writes, from REDIRECTS and `sed -i` only — never inferred.

    A `python3 - <<'PY'` heredoc that opens a file by a computed name is deliberately NOT parsed.
    Guessing the target of a deny hook is how a guard blocks the work that repairs it — the exact
    failure of the identity-override pair, which denied the commits documenting their own fix. So the
    path-gated hooks gain precise coverage here and keep a stated blind spot, rather than a broad one.
    """
    out: list[str] = []
    for masked, raw in segments(cmd or ""):
        for m in _REDIRECT.finditer(masked):
            t = raw[m.start(1) : m.end(1)].strip("'\"")
            if t and not _NOT_A_REPO_PATH.search(t):
                out.append(t)
        sm = _SED_INPLACE.search(masked)
        if sm:
            # `sed -i <expr> path…` — the trailing non-flag words are the files.
            for w in raw[sm.end() :].split():
                w = w.strip("'\"")
                if w and not w.startswith("-") and not _NOT_A_REPO_PATH.search(w):
                    out.append(w)
    return out


def edited(ev: dict) -> tuple[str, str, str]:  # type: ignore[type-arg]
    """`(path, old_text, new_text)` for an Edit/Write event OR a Bash command that writes a file.

    ONE adapter, so a content guard is written once and covers both surfaces. A shell write has no
    "before" text to diff against, so `old` comes back empty and a new-vs-old guard degrades to
    "does the written text contain this at all" — stricter, and right here, because a heredoc
    usually rewrites a whole file rather than amending a line.
    """
    ti = ev.get("tool_input") or {}
    cmd = ti.get("command") or ""
    if cmd:
        targets = write_targets(cmd)
        return (targets[0] if targets else "", "", written_content(cmd))
    return (
        ti.get("file_path") or "",
        ti.get("old_string") or "",
        ti.get("new_string") or ti.get("content") or "",
    )
