#!/usr/bin/env python3
# luxarch:ledger hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Shared helpers for the commit-ledger hooks (record / stop-guard / clear)."""

import json
import os
import subprocess
import sys
from pathlib import Path


def project_dir() -> Path:
    d = os.environ.get("CLAUDE_PROJECT_DIR")
    if d:
        return Path(d)
    try:
        return Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        )
    except Exception:
        return Path.cwd()


def ledger_path() -> Path:
    return project_dir() / ".claude" / ".luxpm-ledger.json"


def read_ledger() -> list[dict[str, object]]:
    try:
        data = json.loads(ledger_path().read_text(encoding="utf-8"))
    except Exception:
        return []
    return data if isinstance(data, list) else []


def write_ledger(entries: list[dict[str, object]]) -> None:
    p = ledger_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(entries, indent=2), encoding="utf-8")


def git(*args: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(project_dir()), *args],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return ""


def session_id() -> str:
    """This agent session's id, from the hook payload if it was read, else the env.

    Claude Code puts `session_id` in every hook event. `read_event()` caches it so a hook that has
    already consumed stdin can still ask. Empty string when unavailable — entries written without a
    session are treated as everyone's, which keeps a pre-upgrade ledger from being ignored.
    """
    # str() at the boundary: the payload is untyped JSON, and an id is only ever compared
    # as a string.
    return str(_EVENT.get("session_id") or os.environ.get("CLAUDE_SESSION_ID", ""))


# A NAMED tuple, not an inline `except (OSError, ValueError)`. Under `target = "py314"` ruff
# formats the inline form to PEP 758's `except OSError, ValueError:`; under py311/py313 it keeps the
# parentheses. So the SAME emitted file has two canonical forms, and an emitted asset is supposed to
# be byte-identical everywhere — in a py314 repo `luxlint --format` rewrote it, `repo.hooks_current`
# then reported drift, and the two guards DEADLOCKED with no local fix (LUXASIF-18).
#
# The fleet declares three targets today (4 guards py311, 7 repos py313, 14 repos py314), so an
# emitted asset must avoid every construct whose canonical formatting is target-dependent. A NAME has
# no parentheses for a formatter to take away.
_PAYLOAD_ERRORS = (OSError, ValueError)

_EVENT: dict[str, object] = {}


def read_event() -> dict[str, object]:
    """Parse the hook event from stdin ONCE and cache it (stdin can only be read once)."""
    global _EVENT
    if not _EVENT:
        try:
            _EVENT = json.load(sys.stdin) or {}
        except _PAYLOAD_ERRORS:
            # Only a missing/malformed payload is tolerated. A bare `except Exception` here hid a
            # NameError (an unimported `sys`) as "no event", so record-commit silently recorded
            # NOTHING while exiting 0 — the same shape as the settings.json data loss.
            _EVENT = {}
    return _EVENT


def mine(entries: list[dict[str, object]]) -> list[dict[str, object]]:
    """The ledger entries belonging to THIS session.

    An entry with no session is included: it predates session stamping, so holding the current agent
    to it is the conservative choice. An entry stamped with a DIFFERENT session is another agent's
    work — it must not block this one, and this one must not log it (that would put wrong commits on
    someone else's ticket).
    """
    me = session_id()
    return [e for e in entries if not e.get("session") or e.get("session") == me]


def others(entries: list[dict[str, object]]) -> list[dict[str, object]]:
    me = session_id()
    return [e for e in entries if e.get("session") and e.get("session") != me]
