#!/usr/bin/env python3
# luxarch:commit-leftover-check hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""After a commit, surface tracked files that are STILL modified.

The safety net behind no-silenced-staging.py: if a staging step failed quietly (or a file was
simply forgotten) the commit lands PARTIAL and the dropped file shows as ` M`. A green local
build hides it, because it builds the working tree, not the commit.

Advisory, never blocking — leaving files out is often deliberate; this just makes it a
conscious choice rather than a discovery three commits later.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _ledger import git


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    if not re.search(
        r"\bgit\s+commit\b", (ev.get("tool_input") or {}).get("command") or ""
    ):
        return 0
    modified = [
        ln
        for ln in git("status", "--porcelain").splitlines()
        if ln[:2].strip() in ("M", "MM", "AM")
    ]
    if not modified:
        return 0
    print(
        "Heads-up — tracked files are still modified after that commit:\n"
        + "\n".join(f"  {m}" for m in modified[:10])
        + "\nIf any of those belonged in the commit, the staging step dropped them.",
        file=sys.stderr,
    )
    return 0


sys.exit(main())
