#!/usr/bin/env python3
# luxarch:confirm-destructive hook v3 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny irreversible destruction of WORK — deleting is the owner's call.

FLEET-AGENT-CONDUCT-STANDARD #6: removing code, data, a volume or history is a scope decision,
never the agent's on its own authority. A denial costs one message to override; an unwanted
recursive delete or a force push costs work that cannot be recovered.

SCOPED, because the first version denied every recursive delete including scratch/temp cleanup —
and a hook that over-fires is a hook that gets switched off (it blocked routine work within
minutes of shipping). What matters is the TARGET: a path inside a project is real work; the
system temp dir, a scratchpad and a tool cache are not. History, volumes and SQL destruction stay
in scope regardless of path.

Commands are read through `_cmdtext.command_text`, so a pattern sitting inside a heredoc or a
quoted literal is DATA and not treated as an execution — the same masking doctrine luxarch's own
line-regex rules use.

PreToolUse(Bash): deny destruction aimed at real work.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _cmdtext import command_text, segments  # sibling helper, loaded by path

# Dangerous wherever it points — history, data stores, whole schemas.
ALWAYS = (
    (
        re.compile(r"\bgit\s+reset\s+--hard\b"),
        "git reset --hard discards working-tree work",
    ),
    (
        re.compile(r"\bgit\s+push\b[^\n]*--force(?!-with-lease)"),
        "force push rewrites pushed history",
    ),
    (
        re.compile(r"\bdocker\s+(?:volume\s+rm|system\s+prune)\b"),
        "docker volume/system prune destroys data",
    ),
    (
        re.compile(r"(?i)\b(?:DROP\s+(?:TABLE|DATABASE|SCHEMA)|TRUNCATE\s+TABLE)\b"),
        "destructive SQL",
    ),
)

# Recursive delete / force-clean: dangerous only when aimed at real work.
PATH_SCOPED = (
    (
        re.compile(r"\brm\s+(?:-[a-zA-Z]*r[a-zA-Z]*f|-[a-zA-Z]*f[a-zA-Z]*r)\b"),
        "recursive force delete",
    ),
    (
        re.compile(r"\bgit\s+clean\s+-[a-zA-Z]*f"),
        "git clean -f deletes untracked files",
    ),
)

# Throwaway locations — deleting here is housekeeping, not destruction of work.
THROWAWAY = re.compile(
    r"/tmp/|/var/tmp/|\$TMPDIR|\$\{TMPDIR|scratchpad|/\.cache/"
    r"|\bnode_modules\b|__pycache__|\.pytest_cache|\.mypy_cache|\.ruff_cache|\.venv\b"
)
# A source-tree path appearing as a target means real work is in range, even alongside a temp path.
REAL_WORK = re.compile(
    r"(?:^|[\s/])(?:src|app|tests|docs|migrations|alembic)(?:/|\s|$)"
)


# A literal shell assignment — `SP=/tmp/x/scratchpad`. Only literal values: a `$(...)`/backtick
# value is unknowable here and is deliberately left unexpanded (it then fails the throwaway test,
# which is the safe direction).
_ASSIGN = re.compile(
    r"""^[ \t]*([A-Za-z_][A-Za-z0-9_]*)=(?!\s)((?:"[^"$`]*"|'[^']*'|[^\s'"$`;|&]+))""",
    re.MULTILINE,
)


def _literal_vars(full_cmd: str) -> dict[str, str]:
    """Literal `VAR=value` assignments anywhere in the command."""
    return {m.group(1): m.group(2).strip("\"'") for m in _ASSIGN.finditer(full_cmd)}


def _expand(text: str, vars_: dict[str, str]) -> str:
    """Substitute known literal vars so a segment carries the path it actually deletes."""
    for name, val in vars_.items():
        text = text.replace("${" + name + "}", val).replace("$" + name, val)
    return text


def _only_throwaway(cmd: str, vars_: dict[str, str] | None = None) -> bool:
    """True when the destruction is confined to throwaway state.

    Conservative on purpose: a source-tree token anywhere in the segment (e.g. a temp path AND a
    repo path in one line) makes it count as touching real work.

    Segments are judged independently (a later unrelated step must not poison an unambiguous
    scratch delete), and that scoping is what made v1 deny `rm -rf "$SP"` when `SP=/tmp/.../
    scratchpad/...` was assigned on an EARLIER line: the delete segment holds only `"$SP"`, so the
    throwaway test saw no path at all and fell through to DENY — while the denial text promised
    that scratchpad cleanup is not blocked. A rule whose message names a case it cannot actually
    recognise is the defect this hook exists to catch, one level up. v3 resolves literal
    assignments from the whole command before judging the segment."""
    resolved = _expand(cmd, vars_) if vars_ else cmd
    return bool(THROWAWAY.search(resolved)) and not REAL_WORK.search(resolved)


def _deny(why: str) -> int:
    print(
        f"DENIED: {why}.\n"
        "Deleting/destroying is the owner's call (conduct standard #6) — verification is not "
        "authorization. Say WHAT you want to remove, the evidence, and whether it is superseded / "
        "never-wired / orphaned, then let the owner rule. (Cleanup confined to /tmp, a scratchpad "
        "or a tool cache is not blocked.)",
        file=sys.stderr,
    )
    return 2


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    if ev.get("tool_name") != "Bash":
        return 0
    raw = (ev.get("tool_input") or {}).get("command") or ""
    cmd = command_text(raw)
    for rx, why in ALWAYS:
        if rx.search(cmd):
            return _deny(why)
    # Judge each SEGMENT on its own, and ask each question of the right text: the VERB on masked
    # text (so a quoted example is not read as an execution), the TARGET on raw text (so a quoted
    # path is still visible). Scanning the whole line made an unrelated later step poison an
    # unambiguous scratch delete; masking the target made a quoted scratch path unrecognisable.
    # Both were caught the same way — the hook blocked its own author mid-task.
    vars_ = _literal_vars(raw)
    for seg_masked, seg_raw in segments(raw):
        for rx, why in PATH_SCOPED:
            if rx.search(seg_masked) and not _only_throwaway(seg_raw, vars_):
                return _deny(why)
    return 0


sys.exit(main())
