#!/usr/bin/env python3
# luxarch:hooks-heartbeat hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Stamp proof that hooks actually EXECUTED — not merely that they are installed.

A hook set can be present on disk, correctly wired in settings.json, and still never run:
disabled at the enterprise/user level, or the harness never loaded them. That is a hollow green
of the worst kind — the repo looks protected and isn't. No static check can see it, because the
evidence of absence is an absence. So the hooks prove themselves: `repo.hooks_wired` reads this
file and goes INERT, never green, when it is missing or stale.

## Written to be SHARED, because repos run several agents at once

The first version stamped `{"at": …, "pid": os.getpid()}` on every single tool call. With more
than one agent in a repo that is a fight with no fixed point: each agent writes ITS pid, every
other agent sees the file change under it, and the churn shows up in every transcript as a
`.hooks-heartbeat (+1 -1)` diff. The pid was per-agent identity in a single shared slot.

Three properties fix it, and all three matter:

* **No pid.** The file answers one question — "did hooks run recently?" — and WHICH agent ran
  them is irrelevant. With identity gone, concurrent agents agree on the content.
* **Throttled.** `repo.hooks_wired` tolerates 30 days; re-stamping hourly is ~700x inside that.
  So the common case writes NOTHING, and the file stops appearing in diffs at all.
* **Atomic.** Write a temp file and `os.replace` it, so two agents crossing the interval at the
  same moment cannot interleave or truncate each other. `os.replace` is atomic on POSIX.

Also ends with a newline — "No newline at end of file" was its own line of noise in every diff.

PreToolUse(*): refresh the stamp if it is stale. Never blocks, never errors out.
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

# Re-stamp at most this often. The rule's staleness limit is 30 days, so an hour is generously
# inside it while keeping the file effectively static — a freshness probe must not become a
# write-amplifier on a shared file.
REFRESH_SECONDS = 3600


def _project_dir() -> Path | None:
    d = os.environ.get("CLAUDE_PROJECT_DIR")
    if d:
        return Path(d)
    try:
        return Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        )
    except Exception:
        return None


def _is_fresh(p: Path) -> bool:
    try:
        stamped = float(json.loads(p.read_text(encoding="utf-8"))["at"])
        return (time.time() - stamped) < REFRESH_SECONDS
    except Exception:
        return False  # absent, truncated, or mid-write by a sibling agent → re-stamp


def main() -> int:
    try:
        root = _project_dir()
        if root is None:
            return 0
        p = root / ".claude" / ".hooks-heartbeat"
        if _is_fresh(p):
            return 0  # the overwhelmingly common path: no write, no diff, no contention
        p.parent.mkdir(parents=True, exist_ok=True)
        # Atomic swap. The temp name carries the pid so two agents never collide on it — that is
        # the one place a pid belongs, and it never reaches the shared file.
        tmp = p.with_suffix(f".{os.getpid()}.tmp")
        tmp.write_text(json.dumps({"at": int(time.time())}) + "\n", encoding="utf-8")
        os.replace(tmp, p)
    except Exception:
        pass  # a heartbeat must never break a tool call
    return 0


sys.exit(main())
