#!/usr/bin/env python3
# luxarch:luxpm-search-before-create hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Search LuxPM for an existing issue BEFORE creating one.

PreToolUse(mcp__luxpm__luxpm_create_issue): deny the create unless this session has SEARCHED LuxPM
since the last issue it created — `luxpm_semantic_search`, or `luxpm_list_issues` with a `search`
term. Listing by label or state alone is not a search: it answers "what is open", not "has this
already been filed".

**Why a hook and not just the standard.** Agents file first and look never. The owner had to unwind
a batch of duplicate audit issues by hand, and nothing in the fleet's docs, hooks or skills said to
search first. The escalation rules said the opposite ("file it the moment you find it"). A written
rule an agent is never made to follow is how that happened, so the rule has one home
(FLEET-AGENT-CONDUCT-STANDARD, "LuxPM: required practices") and this is what makes it stick.

It needs the TURN, which is why it is a hook: whether a search happened earlier in this session is
not in any file a guard can scan. It reads the session transcript Claude Code hands every hook.

**One search per create, not per session.** A search twenty issues ago says nothing about the
twenty-first, so the window restarts at each create. The create being judged is excluded if it is
already in the transcript, so the hook never demands a search *after* itself.

Fails OPEN (no transcript, unreadable line): a hook that blocks on its own uncertainty gets switched
off, taking its real catches with it.
"""

import json
import sys

_CREATE = "mcp__luxpm__luxpm_create_issue"
_SEMANTIC = "mcp__luxpm__luxpm_semantic_search"
_LIST = "mcp__luxpm__luxpm_list_issues"


def _tool_uses(transcript: str) -> list[tuple[str, dict[str, object]]]:
    out: list[tuple[str, dict[str, object]]] = []
    with open(transcript, encoding="utf-8") as fh:
        for line in fh:
            try:
                entry = json.loads(line)
            except ValueError:
                continue
            msg = entry.get("message") if isinstance(entry, dict) else None
            content = msg.get("content") if isinstance(msg, dict) else None
            for block in content if isinstance(content, list) else ():
                if isinstance(block, dict) and block.get("type") == "tool_use":
                    inp = block.get("input")
                    out.append(
                        (
                            str(block.get("name", "")),
                            inp if isinstance(inp, dict) else {},
                        )
                    )
    return out


def _is_search(name: str, inp: dict[str, object]) -> bool:
    if name == _SEMANTIC:
        return True
    return name == _LIST and bool(str(inp.get("search") or "").strip())


def main() -> int:
    try:
        ev = json.load(sys.stdin) or {}
        current = ev.get("tool_input") if isinstance(ev.get("tool_input"), dict) else {}
        uses = _tool_uses(str(ev.get("transcript_path") or ""))
    except Exception:
        return 0  # fail OPEN
    # Drop the create being judged if it is already written to the transcript.
    if uses and uses[-1][0] == _CREATE and uses[-1][1] == current:
        uses = uses[:-1]
    last_create = max((i for i, (n, _) in enumerate(uses) if n == _CREATE), default=-1)
    if any(_is_search(n, inp) for n, inp in uses[last_create + 1 :]):
        return 0
    title = str((current or {}).get("title") or (current or {}).get("text") or "")[:120]
    print(
        "DENIED: search LuxPM for an existing issue before creating one.\n"
        f"You are about to file: {title!r}\n"
        "Run `luxpm_semantic_search` with what you found (or `luxpm_list_issues(search=…)`), across\n"
        "the whole org, not just this project. If a match exists, add to it with `luxpm_add_comment`\n"
        "(new evidence, a new instance, a correction) instead of filing a duplicate; reopen it if it\n"
        "was closed wrongly. File a new issue only when nothing covers it, and say in its body what\n"
        "you searched for. FLEET-AGENT-CONDUCT-STANDARD, 'LuxPM: required practices'.",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
