#!/usr/bin/env python3
# luxarch:luxpm-clear-ledger hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Clear the commit ledger once the work is tracked in LuxPM.

PostToolUse: an activity log, a work log, OR **closing the issue** — all three are tracking the work,
and the stop guard's own message offers all three:

    Log them (luxpm_create_activity / luxpm_log_work, or close the issue) before finishing

Closing was the one it did not honour, so a turn that closed its ticket with a full summary still got
blocked. That is LUXSIGNAL-20 in a sibling hook: a message promising an escape the code never
implemented. The asymmetry that ticket identified applies — closing the issue is state the agent
legitimately controls, so honouring it is honest rather than a loophole.

A bare `update_issue` does NOT clear: bumping progress or editing a description is not completing the
work. The state has to actually move to done/cancelled.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _ledger import read_ledger, write_ledger

_LOGGING_TOOLS = ("luxpm_create_activity", "luxpm_log_work")
_CLOSED_STATES = ("done", "cancelled")


def _tracks_the_work() -> bool:
    """True when this call actually recorded the work, not merely touched the issue."""
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return True  # can't tell → behave as before rather than trapping the turn
    tool = ev.get("tool_name") or ""
    if any(t in tool for t in _LOGGING_TOOLS):
        return True
    if "luxpm_update_issue" in tool:
        state = str((ev.get("tool_input") or {}).get("state") or "").lower()
        return any(c in state for c in _CLOSED_STATES)
    return False


def main() -> int:
    if _tracks_the_work() and read_ledger():
        write_ledger([])
        print("LuxPM: work tracked — commit ledger cleared.", file=sys.stderr)
    return 0


sys.exit(main())
