#!/usr/bin/env python3
# luxarch:luxpm-clear-ledger hook v5 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Clear the commit ledger once the work is tracked in LuxPM.

PostToolUse: an activity log, a work log, a comment, OR **closing the issue** — all of those are
tracking the work, and the stop guard's own message offers them:

    Log them (luxpm_create_activity / luxpm_log_work, or close the issue) before finishing

Closing was the one it did not honour, so a turn that closed its ticket with a full summary still got
blocked. That is LUXSIGNAL-20 in a sibling hook: a message promising an escape the code never
implemented. The asymmetry that ticket identified applies — closing the issue is state the agent
legitimately controls, so honouring it is honest rather than a loophole.

A bare `update_issue` does NOT clear: bumping progress or editing a description is not completing the
work. The state has to actually move to done/cancelled.

LUXPM-222 — three bugs met here, all of one shape: **the tool name matched and the fact was never
read.**

1. `"luxpm_link_commit" in tool` is a PREFIX test, so `luxpm_link_commits` (the batch tool, LuxPM's
   LUXPM-218) entered the singular branch, which read `tool_input["sha"]` — a key the batch tool does
   not have. Empty sha meant "none", so the ledger never drained for the very tool written to drain
   it. Tool names are compared EXACTLY now.
2. The registered matcher did not list `link_commit` at all, so that branch had never received an
   event in its life, and did not list `add_comment` either although the body claimed to honour it.
   Fixed in the wiring; locked by `test_hook_matcher_covers_every_tool_the_body_branches_on`.
3. `write_ledger([])` cleared the WHOLE ledger including a concurrent session's entries — the exact
   cross-session bleed `_ledger.mine()`/`others()` exist to prevent. Only this session's rows clear.

**Which shas cleared comes from the RESPONSE, not the request.** LuxPM returns a per-commit outcome
precisely so a caller can tell what landed ("any sha in the response has landed"), and an
`unresolved` commit has NOT been tracked — clearing it on the strength of having asked would drop it
silently, which is the failure this whole ledger exists to prevent.
"""

import contextlib
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _ledger import mine, read_event, read_ledger, write_ledger

# A comment is a first-class response, so it records the work exactly as an activity does.
_LOGGING_TOOLS = ("luxpm_create_activity", "luxpm_log_work", "luxpm_add_comment")
_CLOSED_STATES = ("done", "cancelled")
# LuxPM's per-commit outcomes: recorded / linked / already_linked landed; unresolved did NOT.
_LANDED = re.compile(r"recorded|linked")
_NOT_LANDED = "unresolved"


def _tool(ev: dict[str, object]) -> str:
    """The bare tool name — `mcp__luxpm__luxpm_log_work` -> `luxpm_log_work`."""
    return str(ev.get("tool_name") or "").rsplit("__", 1)[-1]


def _claimed_shas(tool: str, ti: dict[str, object]) -> list[str]:
    """The shas this CALL asked about (request side) — not yet evidence that any of them landed."""
    if tool == "luxpm_link_commits":
        out = []
        raw = ti.get("commits")
        for c in raw if isinstance(raw, list) else []:
            # An entry is either a bare sha or {sha, message}.
            sha = c.get("sha") if isinstance(c, dict) else c
            if sha:
                out.append(str(sha).strip())
        return out
    sha = str(ti.get("sha") or "").strip()
    return [sha] if sha else []


def _record_landed(rec: dict[str, object]) -> bool:
    """Did THIS commit land, per LuxPM's documented per-commit shape?

        {"sha": "5b5d1b3", "recorded": true, "linked": ["LUXPM-226"],
         "already_linked": [], "unresolved": []}

    `recorded` is a BOOLEAN and `linked`/`already_linked` are LISTS. v3 and v4 both looked for a
    status STRING matching `recorded|linked`, which this shape does not have — so both failed
    identically on a real response, and v4's line-scan fallback could not save it either because the
    JSON is pretty-printed and `"sha": "5b5d1b3",` sits alone on its line. Two releases of fixes
    written against a shape invented in my own test fixtures instead of the contract documented in the
    escalation, which I could not read while `get_context` was refusing my key (LUXPM-226).

    **`recorded: true` is enough.** In LuxPM a commit whose ticket id did not resolve is still
    recorded on the project's commit ledger — only the ISSUE link failed. The work is therefore in the
    tracker and visible, which is the whole thing this ledger exists to ensure, so holding it here
    would block the turn over a typo'd ticket id. The reporter raised exactly that.

    A status string is still honoured if some tracker uses one, but LuxPM is not asked to add a second
    representation of a fact it already publishes.
    """
    if rec.get("recorded") is True:
        return True
    for key in ("linked", "already_linked"):
        v = rec.get(key)
        if isinstance(v, list) and v:
            return True
        if isinstance(v, str) and v.strip():
            return True
    status = str(
        rec.get("status") or rec.get("result") or rec.get("outcome") or ""
    ).lower()
    return bool(status and _NOT_LANDED not in status and _LANDED.search(status))


def _walk_shas(obj: object, out: set[str]) -> None:
    """Every sha this response has a RECORD for, landed or not — so "nothing landed" can be told
    apart from "nothing could be read"."""
    if isinstance(obj, dict):
        sha = obj.get("sha") or obj.get("commit") or obj.get("hash")
        if sha:
            out.add(str(sha).strip())
        for v in obj.values():
            if isinstance(v, str) and v.lstrip()[:1] in "[{":
                with contextlib.suppress(ValueError, TypeError):
                    _walk_shas(json.loads(v), out)
            else:
                _walk_shas(v, out)
    elif isinstance(obj, list):
        for v in obj:
            _walk_shas(v, out)


def _walk_json(obj: object, out: set[str]) -> None:
    if isinstance(obj, dict):
        sha = obj.get("sha") or obj.get("commit") or obj.get("hash")
        if sha and _record_landed(obj):
            out.add(str(sha).strip())
        for v in obj.values():
            # A `text` field may itself hold the JSON payload (MCP content blocks).
            if isinstance(v, str) and v.lstrip()[:1] in "[{":
                with contextlib.suppress(ValueError, TypeError):
                    _walk_json(json.loads(v), out)
            else:
                _walk_json(v, out)
    elif isinstance(obj, list):
        for v in obj:
            _walk_json(v, out)


def _landed(text: str, claimed: list[str]) -> tuple[set[str], bool]:
    """The subset of `claimed` that the response says LANDED. Structure first, then line scanning.

    Always a SUBSET of what this call asked about: the response is an account of those commits, and
    a bare hex token elsewhere in the text is not a verdict on one of them. Without that
    intersection the line-scan fallback could clear a ledger row on an unrelated 7-hex word.

    A single JSON line can carry both a `recorded` and an `unresolved` commit, so a line showing
    BOTH words is unattributable and is skipped rather than guessed at — the conservative direction
    leaves the ledger dirty and the turn blocked, which is loud and recoverable, where over-clearing
    loses a commit in silence.
    """
    found: set[str] = set()
    seen: set[str] = set()
    parsed = None
    with contextlib.suppress(ValueError, TypeError):
        parsed = json.loads(text)
    if parsed is not None:
        _walk_json(parsed, found)
        _walk_shas(parsed, seen)
    if seen:
        # Records WERE parsed. Whatever they say is the answer — including "none of them landed",
        # which is a verdict, not a failure to read. Conflating the two printed "could not read" at a
        # perfectly legible response saying a commit did not land: the same INERT-versus-negative
        # confusion the rules are held to.
        return ({c for c in claimed if any(_same_commit(c, f) for f in found)}, True)
    # PER-SHA PROXIMITY, not per line. v3 skipped any line carrying both a landed and a not-landed
    # word as unattributable, which is right in principle and useless in practice: a JSON response is
    # frequently ONE line holding every outcome. Each claimed sha is located instead, and only the
    # text immediately following it is read — which is where its own verdict sits in JSON and in
    # prose alike. Nothing is inferred from another commit's outcome.
    low = text.lower()
    out: set[str] = set()
    for c in claimed:
        probe = c.strip().lower()[:7]
        if len(probe) < 7:
            continue
        at = 0
        while True:
            i = low.find(probe, at)
            if i < 0:
                break
            at = i + 1
            # Bounded by the LINE, then by distance. An unbounded window spilled into the next
            # line, so a neighbouring `unresolved` stole a landed commit's verdict. JSON never
            # reaches here — it parses structurally above — so a line really is one record's worth.
            eol = low.find("\n", i)
            window = low[i : eol if eol >= 0 else len(low)][:120]
            if _NOT_LANDED in window:
                break  # an explicit non-landing wins, however the rest of the line reads
            if _LANDED.search(window):
                out.add(c)
                break
    return (out, bool(out))


def _collect_text(obj: object, out: list[str]) -> None:
    """Every `text` field in an MCP content-block structure, in order."""
    if isinstance(obj, dict):
        t = obj.get("text")
        if isinstance(t, str):
            out.append(t)
        for v in obj.values():
            _collect_text(v, out)
    elif isinstance(obj, list):
        for v in obj:
            _collect_text(v, out)


def _response_text(ev: dict[str, object]) -> str:
    """The tool's response as TEXT — the payload, not the envelope.

    v3 did `json.dumps(response)` for anything that was not already a string, and an MCP tool does not
    return a string: it returns content blocks, with the per-commit JSON inside a `text` field. Two
    things broke at once. The structural walk found no `sha`/`status` keys, because they were inside a
    JSON *string* rather than parsed structure. And `json.dumps` collapsed everything onto ONE line,
    so the line scan saw `recorded` and `unresolved` together and correctly refused to attribute
    either — v3's own conservative guard, firing on every mixed batch. Net effect: the ledger never
    drained, which is the bug v3 was written to fix. Reported by an adopting agent.
    """
    r = ev.get("tool_response")
    if r is None:
        return ""
    if isinstance(r, str):
        return r
    parts: list[str] = []
    _collect_text(r, parts)
    return "\n".join(parts) if parts else json.dumps(r)


def _decide(ev: dict[str, object]) -> tuple[str, set[str]]:
    """What this tool call proves about the ledger.

    `("all", set())`  — the work is recorded; clear this session's entries.
    `("shas", {...})` — exactly these commits are now attached to an issue; clear only those. The
                        link tools name the shas the ledger is complaining about, so clearing
                        everything on one of them would mark four unlinked commits as tracked
                        because a fifth was. Precision is available, so use it.
    `("none", set())` — touched the issue without recording the work.
    """
    tool = _tool(ev)
    if tool in _LOGGING_TOOLS:
        return ("all", set())
    if tool in ("luxpm_link_commit", "luxpm_link_commits"):
        ti = ev.get("tool_input")
        claimed = _claimed_shas(tool, ti if isinstance(ti, dict) else {})
        text = _response_text(ev)
        if not text.strip():
            # No response to read: the call did not error and there is no evidence either way, so
            # the request is the best available account. (Contrast the branch below, where evidence
            # EXISTS and we failed to read it — guessing there would contradict data in hand.)
            return ("shas", set(claimed))
        landed, readable = _landed(text, claimed)
        if readable:
            return ("shas", landed)
        if not landed:
            print(
                "LuxPM: could not read which commits landed from the response; leaving the ledger "
                "as-is rather than assuming. Re-link, or log the work to clear it.",
                file=sys.stderr,
            )
            return ("none", set())
        return ("shas", landed)
    if tool == "luxpm_update_issue":
        ti = ev.get("tool_input")
        state = str((ti if isinstance(ti, dict) else {}).get("state") or "").lower()
        return (
            ("all", set())
            if any(c in state for c in _CLOSED_STATES)
            else ("none", set())
        )
    return ("none", set())


def _same_commit(a: str, b: str) -> bool:
    """Shas match if either is a prefix of the other — the ledger may hold a short sha."""
    a, b = a.strip().lower(), b.strip().lower()
    n = min(len(a), len(b))
    return bool(n >= 7 and a[:n] == b[:n])


def main() -> int:
    ev = read_event()
    kind, shas = _decide(ev)
    entries = read_ledger()
    if not entries or kind == "none":
        return 0
    # Only ever clear THIS session's rows; another agent's unlogged commits are not ours to mark
    # tracked, and wiping them would put the wrong commits beyond the reach of its own stop guard.
    ours = {id(e) for e in mine(entries)}
    if kind == "all":
        keep = [e for e in entries if id(e) not in ours]
        write_ledger(keep)
        left = f" ({len(keep)} from another session left)" if keep else ""
        print(f"LuxPM: work tracked — commit ledger cleared{left}.", file=sys.stderr)
        return 0
    keep = [
        e
        for e in entries
        if id(e) not in ours
        or not any(_same_commit(str(e.get("sha") or ""), s) for s in shas)
    ]
    if len(keep) != len(entries):
        gone = len(entries) - len(keep)
        mine_left = len([e for e in keep if id(e) in ours])
        left = f"{mine_left} still unlogged" if mine_left else "ledger clear"
        print(f"LuxPM: {gone} commit(s) linked — {left}.", file=sys.stderr)
        write_ledger(keep)
    return 0


sys.exit(main())
