#!/usr/bin/env python3
# luxarch:no-ai-attribution hook v2 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny commits / PRs carrying AI attribution.

House rule (CLAUDE.md, persistent): no `Co-Authored-By: Claude`, no "Generated with Claude
Code" in any commit or PR. The harness nudges for it, so this makes the rule mechanical.
A human Co-Authored-By trailer (not Claude/Anthropic) is fine and passes through.

PreToolUse(Bash): deny a git commit / gh pr create|edit whose text carries AI attribution.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from _cmdtext import command_text

AUTHORING = re.compile(r"\bgit\s+commit\b|\bgh\s+pr\s+(?:create|edit)\b", re.IGNORECASE)
ATTRIB = re.compile(
    r"(?i)co-authored-by:\s*[^\n]*(?:claude|anthropic|noreply@anthropic)"
    r"|generated\s+with\s+\[?claude"
    r"|\U0001F916\s*generated"
)


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    if ev.get("tool_name") != "Bash":
        return 0
    # TWO questions, two texts — the split `_cmdtext.segments` documents.
    #
    # "Is an authoring command actually being RUN?" is about the executable command, so it is asked
    # of MASKED text. It used to be asked of the raw string, and the scope claim this comment
    # carried ("prose about attribution elsewhere cannot trip it") was therefore false: any heredoc
    # whose BODY mentioned the authoring verb satisfied the scope test, so writing a test file or a
    # doc that quoted both an attribution trailer and that verb was denied. Found by dogfooding —
    # this hook blocked the very commit adding the regression test for its neighbour, the same
    # over-fire class as LUXUPT-76 one hook over.
    #
    # "Does the payload carry attribution?" is about what the command CARRIES, so it stays RAW —
    # the message IS the quoted payload, and masking it would blind this hook entirely.
    cmd = (ev.get("tool_input") or {}).get("command") or ""
    if not AUTHORING.search(command_text(cmd)) or not ATTRIB.search(cmd):
        return 0
    print(
        "DENIED: no AI attribution in commits or PRs.\n"
        "Remove the Co-Authored-By / 'Generated with Claude Code' line and commit again. "
        "(A human co-author trailer is fine.)",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
