#!/usr/bin/env python3
# luxarch:no-agent-deferral hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny an AGENT adding a deferral / allowlist entry to a guard config.

The guard reads `.luxarch.toml` as DATA — it can never tell an owner-approved
`[rules.deferred]` from an agent quietly routing around a red. This hook can: it sees the
edit being made. Fleet rule (CLAUDE.md, FLEET-AGENT-CONDUCT-STANDARD #5/#7): a red is fixed
by aligning the code or escalated to the maintainer — deferrals and allowlists are the repo
OWNER's call, with a written evidence line, never the agent's.

PreToolUse(Edit|Write): deny when the new content adds a `[rules.deferred]` /
`[allowlist...]` entry the old content didn't have. The owner edits these by hand.
"""

import json
import re
import sys

CONFIGS = (".luxarch.toml", ".luxlint.toml", ".luxaudit.toml")
MARKERS = (
    re.compile(r"^\s*\[rules\.deferred\]", re.M),
    re.compile(r"^\s*\[\[?allowlist", re.M),
    re.compile(r"^\s*deferred\s*=", re.M),
)


def count(text: str) -> int:
    return sum(len(m.findall(text or "")) for m in MARKERS)


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    ti = ev.get("tool_input") or {}
    path = ti.get("file_path") or ""
    if not any(path.endswith(c) for c in CONFIGS):
        return 0
    old = ti.get("old_string") or ""
    new = ti.get("new_string") or ti.get("content") or ""
    if count(new) <= count(old):
        return 0
    print(
        "DENIED: this edit adds a deferral/allowlist entry to a guard config.\n"
        "A red is fixed by ALIGNING the code, or ESCALATED to the guard maintainer — it is "
        "never deferred to green by the agent. `[rules.deferred]` and every allowlist entry "
        "are the repo OWNER's call and need a written evidence line.\n"
        "If you believe the rule is genuinely wrong: say so, cite the rule id and its "
        "--playbook, and let the owner decide.",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
