#!/usr/bin/env python3
# luxarch:no-github-issues hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Escalations, bugs and product requests go in LuxPM. Never a GitHub issue.

PreToolUse(Bash): deny `gh issue create` / `gh api .../issues -X POST`. LuxPM is the fleet's tracker;
GitHub holds code and Releases and nothing else.

**Why a hook and not just the standard.** FLEET-ONBOARDING-STANDARD used to sanction
`github.com/luxardolabs/<guard>` as a fallback *"if your repo is not connected to LuxPM yet"*. An
agent took it while its own LuxPM project was live and working, filing four issues across two repos,
and cited the document correctly when challenged. The conditional was the defect: an escape hatch on
an escalation path gets applied wherever it half-fits, and the owner then finds out from the wrong
tracker. The prose is deleted; this is what makes the deletion stick.

It denies CREATION only. Reading is fine and often necessary — `gh issue list` to find what a previous
agent filed in the wrong place, `gh issue view`, and `gh issue delete` to clean it up. A guard that
blocked the cleanup would trap the repair, which is the failure this hook family has shipped before.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _cmdtext import segments

# Asked of the MASKED text: "is this verb being RUN?" — a heredoc or a quoted string that merely
# mentions `gh issue create` (a doc being written, this very file) is data, not an execution.
_GH_ISSUE_CREATE = re.compile(r"\bgh\b[^\n]*?\bissue\b[^\n]*?\bcreate\b")
# `gh api repos/<o>/<r>/issues -X POST` / `--method POST` is the same act by another route.
_GH_API_ISSUE_POST = re.compile(r"\bgh\b[^\n]*?\bapi\b[^\n]*?/issues\b")
_POST = re.compile(r"-X[ \t]*POST|--method[ \t]*POST|-f[ \t]|--field[ \t]")
# curl against the REST API, for completeness — same act, no gh.
_CURL_ISSUE_POST = re.compile(r"\bcurl\b[^\n]*?api\.github\.com[^\n]*?/issues\b")


def _creates_a_github_issue(masked: str) -> bool:
    if _GH_ISSUE_CREATE.search(masked):
        return True
    if _GH_API_ISSUE_POST.search(masked) and _POST.search(masked):
        return True
    return bool(_CURL_ISSUE_POST.search(masked) and _POST.search(masked))


def main() -> int:
    ev: dict[str, object] = {}
    try:
        ev = json.load(sys.stdin) or {}
    except Exception:
        return 0  # hooks fail OPEN
    ti = ev.get("tool_input")
    cmd = str((ti if isinstance(ti, dict) else {}).get("command") or "")
    if not any(_creates_a_github_issue(masked) for masked, _raw in segments(cmd)):
        return 0
    print(
        "DENIED: escalations and bug reports go in LuxPM, never GitHub Issues.\n"
        "File it in YOUR OWN repo's LuxPM project with `luxpm_create_issue`, label it "
        "`fleet-escalation`, and name the target guard in the title — the maintainer sweeps that "
        "label across every project and picks it up where you filed it.\n"
        "Escalating about LuxPM itself? It has its own LuxPM project, like every other repo.\n"
        "Genuinely have no LuxPM project? Say so to the owner in one line and keep the full "
        "escalation text in that reply; they create the project and you file it properly. Do not "
        "invent a channel.\n"
        "See luxarch --doc FLEET-ONBOARDING-STANDARD §3a. Reading and DELETING issues is allowed — "
        "only creation is denied, so you can still clean up ones filed in the wrong place.",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
