#!/usr/bin/env python3
# luxarch:no-golden-edit hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny hand-editing a frozen parity golden.

`tests/parity/*.golden` are byte-exact fixtures — they are the TOOL-regression gate. Editing
one by hand to match new output destroys the very thing that proves a change was intentional.
The only correct way to change a golden is `make parity-update`, then READ the diff and
confirm every line changed on purpose.

PreToolUse(Edit|Write): deny writes to a .golden fixture.
"""

import json
import sys


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    path = (ev.get("tool_input") or {}).get("file_path") or ""
    if not path.endswith(".golden"):
        return 0
    print(
        "DENIED: parity goldens are never hand-edited.\n"
        "Run `make parity-update`, then read `git diff tests/parity/` and confirm EVERY change "
        "is intended. Hand-editing a golden to match new output removes the only check that "
        "the output changed on purpose.",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
