#!/usr/bin/env python3
# luxarch:no-gate-bypass hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny commands that bypass the gate (`--no-verify`, SKIP=, deselecting failures).

The fleet has ONE gate: `make check`, plus the committed git hooks. `git commit --no-verify`
skips the secret scan; `pytest --deselect`/`-k` used to route around a failure turns a red
suite green without fixing anything. Both are 'route around the guard', which the conduct
standard bans outright.

PreToolUse(Bash): deny the bypass flags on commit/push and the gate-dodging test invocations.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _cmdtext import command_text  # sibling helper, loaded by path

BYPASS = (
    (
        re.compile(r"\bgit\s+(?:commit|push)\b[^\n]*--no-verify"),
        "--no-verify skips the committed git hooks (incl. the secret scan)",
    ),
    (re.compile(r"\bSKIP=\S+\s+git\s+commit"), "SKIP= disables hooks for this commit"),
    (
        re.compile(r"\bpytest\b[^\n]*--deselect\b"),
        "--deselect drops a failing test instead of fixing it",
    ),
    (
        re.compile(r"\bgit\s+push\b[^\n]*--force(?!-with-lease)\b"),
        "--force can destroy pushed history (use --force-with-lease, and say why)",
    ),
)


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    if ev.get("tool_name") != "Bash":
        return 0
    cmd = command_text((ev.get("tool_input") or {}).get("command") or "")
    for rx, why in BYPASS:
        if rx.search(cmd):
            print(
                f"DENIED: {why}.\n"
                "The fleet gate is `make check` + the committed hooks — a red is fixed or "
                "escalated, never routed around. If this is genuinely necessary, ask the owner.",
                file=sys.stderr,
            )
            return 2
    return 0


sys.exit(main())
