#!/usr/bin/env python3
# luxarch:no-identity-override hook v3 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny an identity override — by FLAG or by repo-local config. Commit as the fleet identity, always.

CLAUDE.md non-negotiable: commit as `luxardolabs` via the GLOBAL git config (the GitHub
noreply address). Passing a real email on the command line EXPOSES it in the commit and
GitHub blocks the push — and the fix is a rewrite. Documented everywhere, enforced nowhere
until now.

**Two routes, and v2 only guarded one.** The `-c` flag is one command by one agent. A repo-local
`[user]` section in `.git/config` applies to EVERY commit in that clone, silently, forever — git
resolves local over global — and it survives onboarding, a full guard burn-down and
`repo.hooks_wired` reporting PASS throughout. A repo wrote **968 commits** mis-authored that way with
this hook installed and wired the entire time, firing on none of them, and it was found because the
owner noticed the author was wrong, not because anything flagged it (LUXTASTE-338).

So this now asserts the FACT (what identity will this commit actually carry?) as well as the spelling
(is an override flag present?). Both checks are needed: a `-c` flag does not change stored config, so
`git config --get` cannot see it, and stored config does not appear in the command text.

The config check needs **no hardcoded identity**: the fleet identity lives in the GLOBAL config, so
the defect is a LOCAL value that differs from it. A local value identical to the global one is
redundant but harmless and is allowed — otherwise the hook would fire on a repo that simply pinned
the same thing twice.

PreToolUse(Bash): deny an identity override on a git command.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from _cmdtext import command_text

OVERRIDE = re.compile(
    r"\bgit\b[^\n]*-c\s*(?:user\.email|user\.name)\s*=", re.IGNORECASE
)
# Only commands that STAMP an identity into an object. A `git log`/`git status` carrying a wrong local
# config is not yet a defect, and denying those would make the hook something people switch off.
STAMPS_IDENTITY = re.compile(
    r"\bgit\b[^\n]*\b(?:commit|tag|revert|cherry-pick|merge|am)\b"
)


def _git(*args: str) -> str:
    """A git config read that can never break the turn: any failure reads as 'not set'."""
    try:
        r = subprocess.run(
            ["git", *args], capture_output=True, text=True, timeout=5, check=False
        )
        return r.stdout.strip()
    except Exception:
        return ""


def _local_override() -> str | None:
    """The identity key whose LOCAL value shadows the global fleet identity, if any."""
    for key in ("user.name", "user.email"):
        local = _git("config", "--local", "--get", key)
        if not local:
            continue
        if local != _git("config", "--global", "--get", key):
            return key
    return None


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    if ev.get("tool_name") != "Bash":
        return 0
    # MASKED, not raw. `-c user.email=` is about the FLAG on the executable command, so it must be
    # read from the executable part only — a heredoc body or a quoted literal carrying the pattern is
    # DATA the command transports, not an override being performed. Reading raw text denied a plain
    # `git commit` whose MESSAGE quoted the pattern, which is how this was found: the commit
    # documenting the hook set could not be written (LUXUPT-76). A hook that over-fires is a hook
    # that gets switched off. `confirm-destructive.py` has always read masked text; this one imported
    # the helper and never called it. (`no-ai-attribution` deliberately does NOT mask — there the
    # message IS the payload being judged.)
    cmd = (ev.get("tool_input") or {}).get("command") or ""
    masked = command_text(cmd)
    if not OVERRIDE.search(masked):
        # No flag — but stored config is the route v2 could not see, and it is the worse one.
        if STAMPS_IDENTITY.search(masked):
            key = _local_override()
            if key:
                print(
                    f"DENIED: this repo's LOCAL git config overrides `{key}`, so every commit here "
                    f"is authored with the wrong identity — silently, on every commit, not just "
                    f"this one.\n"
                    f"  current local:  {_git('config', '--local', '--get', key)!r}\n"
                    f"  fleet (global): {_git('config', '--global', '--get', key)!r}\n"
                    f"Fix: git config --local --unset {key}\n"
                    f"A repo wrote 968 commits mis-authored this way with this hook installed and "
                    f"firing on none of them, because v2 matched only the `-c` FLAG form.",
                    file=sys.stderr,
                )
                return 2
        return 0
    print(
        "DENIED: never override the git identity with `-c user.email=` / `-c user.name=`.\n"
        "Commit with a plain `git commit` — the GLOBAL config already carries the fleet "
        "identity (luxardolabs + the GitHub noreply address). Passing a real email exposes it "
        "in the commit and GitHub blocks the push.",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
