#!/usr/bin/env python3
# luxarch:no-silenced-staging hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny MUTATING git commands that silence stderr (`2>/dev/null`).

Earned the hard way: `git add` with a bad pathspec fails ATOMICALLY — it stages nothing,
including the valid files beside it — and reports on stderr. Silence that and the failure is
invisible: the file never enters the commit, and a green LOCAL build hides it (it builds the
working tree, not the commit). That chain broke origin/main once; the deleted type was
referenced for several commits before a rebase finally tripped on it.

Read-only git with `2>/dev/null` (status/show/diff/log/rev-parse) is common and fine.

PreToolUse(Bash): deny `git (add|rm|mv|commit|apply|restore|stash)` + stderr-to-null.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _cmdtext import command_text  # sibling helper, loaded by path

MUTATING = re.compile(r"\bgit\s+(?:add|rm|mv|commit|apply|restore|stash)\b")
SILENCED = re.compile(r"2>\s*(?:/dev/null|&\s*1\s*>\s*/dev/null)|2>&1\s*>\s*/dev/null")


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    if ev.get("tool_name") != "Bash":
        return 0
    cmd = command_text((ev.get("tool_input") or {}).get("command") or "")
    # Scope the pairing to ONE command segment. A compound line routinely silences an
    # unrelated call earlier on (a docker/build step) and then runs a clean `git add` — matching
    # the whole string reads that as a silenced staging command. A hook that over-fires gets
    # switched off, so both halves must occur in the SAME segment. (Found by dogfooding: this
    # hook denied its own release commit.)
    segments = re.split(r"&&|\|\||;|\n|\|", cmd)
    if not any(MUTATING.search(seg) and SILENCED.search(seg) for seg in segments):
        return 0
    print(
        "DENIED: never silence stderr on a mutating git command.\n"
        "`git add` fails ATOMICALLY on a bad pathspec — it stages NOTHING and says so on "
        "stderr. Hiding that produces a silently partial commit which a local build cannot "
        "catch. Drop the `2>/dev/null` and read the error.",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
