#!/usr/bin/env python3
# luxarch:no-test-weakening hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny weakening a test to make a suite pass (skip/xfail markers, deleted assertions).

A skipped test reads as a pass. `24 passed, 21 skipped` presenting as coverage is the most
dangerous line in FLEET-VERIFICATION-STANDARD — a suite that can't fail proves nothing. When
a test fails you fix the code or fix a genuinely-wrong test with the owner; you never mark it
skip/xfail to get to green.

PreToolUse(Edit|Write): deny when an edit to a test file ADDS a skip/xfail marker.
"""

import json
import re
import sys

WEAKEN = re.compile(
    r"@pytest\.mark\.(?:skip|xfail)\b|pytest\.skip\(|@unittest\.skip|\.skip\s*=\s*True"
)


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    ti = ev.get("tool_input") or {}
    path = ti.get("file_path") or ""
    if "test" not in path:
        return 0
    old, new = (
        ti.get("old_string") or "",
        ti.get("new_string") or ti.get("content") or "",
    )
    if len(WEAKEN.findall(new)) <= len(WEAKEN.findall(old)):
        return 0
    print(
        "DENIED: this edit skips/xfails a test.\n"
        "A skipped test reads as a pass — that is the hollow green. Fix the code under test, "
        "or take a genuinely-wrong test to the owner. If the skip is legitimate (an external "
        "dependency that truly cannot run here), say so and let the owner decide.",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
