#!/usr/bin/env python3
# luxarch:unpushed-stop-guard hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Refuse to end the turn with commits sitting unpushed — unless a hold is RECORDED.

FLEET-AGENT-CONDUCT-STANDARD: "Nothing is done until its gate is green AND the work is pushed.
A local-only pile is invisible and not done." A repo carrying a dozen unpushed commits is the
exact failure this catches, and it is invisible to every file-based guard.

But the hold is often CORRECT. Pushing is outward-facing; an agent told to wait for
authorization should NOT push, and blocking it forever turns the conduct standard against
itself — one wasted turn per attempt, indefinitely (LUXSIGNAL-20 hit exactly that across four
consecutive turns). The sibling `luxpm-stop-guard` blocks on state the agent controls, so its
override is honest; this one blocks on an action requiring someone ELSE's consent, so it must
accept a recorded reason rather than demand compliance.

The first version's message named an escape — "or say explicitly why it is being held back" —
that the code never implemented. So the escape is now a FACT the hook can read: write the
reason to `.claude/.push-hold`. It is recorded in the tree, surfaced every turn so it cannot
rot into a silent exemption, and cleared with `rm` + push.

Stop hook: block while HEAD is ahead of upstream AND no hold is recorded. No upstream /
detached HEAD passes. Self-contained on purpose — a hook must not depend on import-path
manipulation to run.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

HOLD = ".claude/.push-hold"


def project_dir() -> Path:
    d = os.environ.get("CLAUDE_PROJECT_DIR")
    if d:
        return Path(d)
    try:
        return Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        )
    except Exception:
        return Path.cwd()


def git(*args: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(project_dir()), *args],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return ""


def _already_blocked() -> bool:
    """True when this Stop hook has ALREADY blocked once this turn.

    Claude Code sets `stop_hook_active` on the re-entry after a Stop hook blocks. Honouring it is
    what makes a Stop guard a reminder rather than a trap: it gets one turn to put the obligation
    in front of the agent, then stands down. Without it the hook loops until the harness
    force-overrides — nine consecutive turns, observed live — and an agent that legitimately
    cannot comply (a push awaiting authorization) has no way out at all."""
    try:
        return bool(json.load(sys.stdin).get("stop_hook_active"))
    except Exception:
        return False


def main() -> int:
    if _already_blocked():
        return 0
    upstream = git("rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}")
    if not upstream:
        return 0  # no upstream configured — nothing to be ahead of
    ahead = git("rev-list", "--count", f"{upstream}..HEAD")
    if not ahead.isdigit() or int(ahead) == 0:
        return 0

    try:
        reason = (project_dir() / HOLD).read_text(encoding="utf-8").strip()
    except OSError:
        reason = ""
    if reason:
        # A recorded hold is a DECISION, not a dodge — print it every turn so it stays visible
        # and cannot quietly become a permanent exemption.
        print(
            f"{ahead} commit(s) held back from {upstream} — recorded in {HOLD}:\n"
            f"  {reason}\n"
            f"Clear it (`rm {HOLD}`) and push once the hold no longer applies.",
            file=sys.stderr,
        )
        return 0

    print(
        f"{ahead} commit(s) are committed but NOT pushed to {upstream}.\n"
        "Local-only work is invisible and does not count as done — `git push` before finishing.\n"
        "If the hold is DELIBERATE (waiting on authorization for an outward-facing push, a "
        "release not yet approved), record it and this stands down:\n"
        f'  echo "why it is held" > {HOLD}',
        file=sys.stderr,
    )
    return 2


sys.exit(main())
